# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(1, 'Top'), (2, 'Bottom'), (3, 'Overall'), (4, 'Shoe'), (5, 'Accessory')], null=True, verbose_name='Product Type')),
                ('sex', models.IntegerField(choices=[(1, 'Men'), (2, 'Women'), (3, 'Unisex')], verbose_name='Sex')),
                ('brand', models.CharField(blank=True, max_length=64, verbose_name='Brand')),
                ('size', models.CharField(max_length=8, verbose_name='Size')),
                ('picture', models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture')),
            ],
        ),
    ]
