# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161004_1250'),
        ('product', '0006_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User')),
            ],
        ),
    ]
