# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.product_image_path_name, verbose_name='Product Image'),
        ),
    ]
