# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='picture',
        ),
    ]
