# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productimage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
