# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20161130_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='invoice_number',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Invoice Number'),
        ),
    ]
