# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20161130_1658'),
        ('product', '0014_auto_20161130_1649'),
    ]

    operations = [
    ]
