# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, verbose_name='Unique id')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sex', models.IntegerField(choices=[(1, 'Men'), (2, 'Women'), (3, 'Unisex')], verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('first_name', models.CharField(max_length=64, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=64, verbose_name='Lastname')),
                ('address', models.TextField(null=True, verbose_name='Address')),
            ],
        ),
    ]
