# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161004_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'member'), (2, 'admin')], default=1, verbose_name='User Type'),
        ),
    ]
