# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.user_image_path_name, verbose_name='User Image'),
        ),
    ]
