# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_auto_20161127_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to=webadmin.models.payment_image_path_name, verbose_name='Payment Image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
            ],
        ),
    ]
