# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Total Amount'),
        ),
    ]
